### CreateChat
POST http://localhost:8000/chats/create
Content-Type: application/json

{
	"firstUser": "dave",
	"secondUser": "lucy"
}

### GetAllUserChats
GET  http://localhost:8000/chats/userChats/dave
Content-Type: application/json

### FindChat
GET  http://localhost:8000/chats/chat/57445d60-7b6d-4b9a-8adb-acd3e38df96d
Content-Type: application/json
