### CreateMessage
POST http://localhost:8000/messages/create
Content-Type: application/json

{
	"sender": "dave",
	"chatId": "e643469f-8c26-4835-8aab-a3465702de91",
	"text": "Hello, John!"
}

### GetAllMessages
GET  http://localhost:8000/messages/all/9ee47bce-4802-4ddf-b2b6-660edc3888b6
Content-Type: application/json

### EditMessage
PATCH   http://localhost:8000/messages/edit
Content-Type: application/json

{
	"msgId": "b65c6d25-8de5-49ff-aed6-e1054631fbc7",
	"newText": "Hi!!"
}

### DeleteMessage
DELETE    http://localhost:8000/messages/delete
Content-Type: application/json

{
	"msgId": "b65c6d25-8de5-49ff-aed6-e1054631fbc7"
}