### CreateMessage
POST http://localhost:8000/messages/create
Content-Type: application/json

{
	"sender": "dave",
	"chatId": "e643469f-8c26-4835-8aab-a3465702de91",
	"text": "Hello, John!"
}

### GetAllMessages
GET  http://localhost:8000/messages/all/b58f6dc2-bec3-4d7d-902c-5bd6df29afea
Content-Type: application/json

### EditMessage
PATCH   http://localhost:8000/messages/edit
Content-Type: application/json

{
	"msgId": "7e74acba-b33a-4ec1-b234-519eb1b396c6",
	"newText": "Hi!!"
}

### DeleteMessage
DELETE    http://localhost:8000/messages/delete
Content-Type: application/json

{
	"msgId": "4ca7d32f-5ca1-477c-9054-f02183454787"
}