### Register
POST http://localhost:8000/users/register
Content-Type: application/json

{
	"login": "john",
	"firstName": "John",
	"lastName": "Doe",
	"password": "test"
}

### Login
POST http://localhost:8000/users/login
Content-Type: application/json

{
	"login": "jane",
	"password": "qweqwe"
}

### GetOneUser
GET http://localhost:8000/users/user/dave
Content-Type: application/json


### GetAllUsers
GET http://localhost:8000/users/users
Content-Type: application/json
